"""10 Faculdades da Universidade Sintética Transversal.

Cada faculdade contém: domínio, subdisciplinas, conceitos fundamentais,
métodos de pesquisa, tradições epistemológicas e ferramentas-chave.
"""

from __future__ import annotations
from dataclasses import dataclass, field
from typing import List, Dict, Optional


@dataclass
class Faculdade:
    """Uma faculdade/unidade acadêmica na universidade sintética."""
    id: str
    nome: str
    nome_en: str
    descricao: str
    subdisciplinas: List[str] = field(default_factory=list)
    conceitos: List[str] = field(default_factory=list)
    metodos_pesquisa: List[str] = field(default_factory=list)
    tradicoes_epistemologicas: List[str] = field(default_factory=list)
    ferramentas: List[str] = field(default_factory=list)

    def __post_init__(self):
        # Ensure conceitos are deduplicated and lowercased
        seen = set()
        deduped = []
        for c in self.conceitos:
            key = c.lower().strip()
            if key not in seen:
                seen.add(key)
                deduped.append(c.strip())
        self.conceitos = deduped

    def __len__(self) -> int:
        return len(self.conceitos)

    def __repr__(self) -> str:
        return f"<Faculdade {self.id}: {self.nome} ({len(self.conceitos)} conceitos)>"


# =============================================================================
# 1. CIÊNCIAS HUMANAS (Human Sciences)
# =============================================================================
HUMAN_SCIENCES = Faculdade(
    id="human_sciences",
    nome="Ciências Humanas",
    nome_en="Human Sciences",
    descricao="Filosofia, psicologia, sociologia, antropologia e educação — "
               "o estudo da condição humana em suas dimensões subjetiva, social e cultural.",
    subdisciplinas=[
        "Filosofia", "Psicologia", "Sociologia", "Antropologia",
        "Educação", "Pedagogia", "Teologia", "Ética", "Estética", "Fenomenologia",
        "Psicanálise", "Teoria Crítica", "Hermenêutica",
        "Filosofia da Mente", "Filosofia da Ciência", "Filosofia Política",
        "Filosofia da Linguagem", "Lógica", "Metafísica", "Epistemologia",
        "Axiologia", "Filosofia da Educação", "Filosofia da Tecnologia",
        "Neurociência Cognitiva",
    ],
    conceitos=[
        # Filosofia (original)
        "consciência", "ser", "existência", "liberdade", "ética", "moral",
        "justiça", "verdade", "conhecimento", "crença", "dúvida", "certeza",
        "sujeito", "objeto", "fenômeno", "noumeno", "transcendental",
        "dialética", "alteridade", "reconhecimento", "poder", "discurso",
        "estrutura", "agência", "habitus", "campo", "capital simbólico",
        "inconsciente", "recalque", "transferência", "sintoma", "desejo",
        "intersubjetividade", "intencionalidade", "corpo", "afeto",
        "emoção", "razão", "intuição", "imaginação", "memória",
        "percepção", "linguagem", "símbolo", "mito", "rito",
        "sagrado", "profano", "experiência", "sentido", "valor",
        "norma", "lei", "contrato social", "vontade geral",
        "reificação", "alienação", "fetiche", "mais-valia",
        "indivíduo", "comunidade", "sociedade civil", "estado",
        "espaço público", "esfera pública", "opinião pública",
        "civilização", "cultura", "natureza", "técnica", "humanismo",
        "pós-humanismo", "transumanismo", "animalidade",
        "vulnerabilidade", "cuidado", "responsabilidade", "dignidade",
        # Filosofia expandida
        "identidade", "diferença", "gênero", "raça", "classe", "ideologia",
        "hegemonia", "biopolítica", "governamentalidade", "disciplina",
        "normalização", "resistência", "emancipação", "autonomia",
        "platonismo", "aristotelismo", "estoicismo", "epicurismo",
        "ceticismo", "neoplatonismo", "patrística", "escolástica",
        "racionalismo cartesiano", "empirismo humeano", "idealismo alemão",
        "kantianismo", "hegelianismo", "schopenhauer", "nietzsche",
        "marxismo", "existencialismo sartreano", "fenomenologia husserliana",
        "hermenêutica gadameriana", "pragmatismo americano",
        "filosofia analítica", "filosofia da linguagem ordinária",
        "teoria crítica frankfurtiana", "pós-estruturalismo francês",
        "ontologia", "metafísica", "epistemologia", "axiologia",
        "lógica proposicional", "lógica de predicados", "lógica modal",
        "filosofia da mente", "qualia", "problema mente-corpo",
        "funcionalismo", "fisicalismo", "dualismo", "behaviorismo lógico",
        "teoria da identidade", "externalismo semântico", "internalismo",
        "livre-arbítrio", "determinismo", "compatibilismo", "incompatibilismo",
        "filosofia da ciência", "indução", "dedução", "abdução", "falseabilismo",
        "programa de pesquisa", "paradigma", "revolução científica",
        "realismo científico", "antirrealismo", "instrumentalismo",
        "filosofia da tecnologia", "fenomenologia da técnica",
        "determinismo tecnológico", "construção social da tecnologia",
        # Pedagogia / Educação
        "pedagogia", "educação", "ensino", "aprendizagem", "didática",
        "currículo", "escola", "professor", "aluno", "sala de aula",
        "avaliação educacional", "planejamento pedagógico",
        "desenvolvimento infantil", "psicologia educacional",
        "teoria da aprendizagem", "behaviorismo educacional",
        "cognitivismo educacional", "construtivismo piagetiano",
        "sócio-construtivismo vygotskyano", "aprendizagem significativa ausubeliana",
        "pedagogia freireana", "pedagogia crítico-social",
        "pedagogia montessoriana", "pedagogia waldorf", "pedagogia freinet",
        "educação inclusiva", "educação especial", "educação a distância",
        "tecnologia educacional", "gamificação educacional",
        "metodologias ativas", "aprendizagem baseada em problemas",
        "sala de aula invertida", "ensino híbrido", "blended learning",
        "andragogia", "educação de adultos", "educação continuada",
        "formação de professores", "saberes docentes", "prática pedagógica",
        "gestão educacional", "projeto político-pedagógico",
        "educação infantil", "ensino fundamental", "ensino médio",
        "educação superior", "universidade", "extensão universitária",
        "pesquisa educacional", "etnografia educacional",
        "educação ambiental", "educação para a paz",
        "educação em direitos humanos", "educação intercultural",
        "letramento", "alfabetização", "numeramento",
        "avaliação da aprendizagem", "instrumentos avaliativos",
        "repetência", "evasão escolar", "permanência",
        "educação popular", "educação do campo", "educação indígena",
        "psicopedagogia", "neuroeducação", "neurociência educacional",
        "multiletramentos", "competências socioemocionais",
        "BNCC", "Base Nacional Comum Curricular", "diretrizes curriculares",
        # Psicologia expandida
        "psicologia", "psique", "mente", "comportamento", "cognição",
        "psicologia clínica", "psicologia social", "psicologia organizacional",
        "psicologia do desenvolvimento", "psicologia da personalidade",
        "psicologia cognitiva", "psicologia experimental", "psicometria",
        "psicopatologia", "psicodiagnóstico", "avaliação psicológica",
        "psicoterapia", "terapia cognitivo-comportamental", "TCC",
        "psicanálise freudiana", "psicologia analítica junguiana",
        "psicologia humanista", "gestalt-terapia", "logoterapia",
        "teoria dos arquétipos", "inconsciente coletivo", "individuação",
        "neuropsicologia", "neurociência cognitiva", "plasticidade neural",
        "desenvolvimento moral", "desenvolvimento psicossocial",
        "teoria do apego", "estilos parentais", "vínculo", "relação materna",
        "trauma psicológico", "estresse", "ansiedade", "depressão",
        "resiliência", "coping", "regulação emocional", "inteligência emocional",
        "motivação", "emoção", "sentimento", "afeto", "humor",
        "percepção social", "atribuição causal", "estereótipo", "preconceito",
        "dissonância cognitiva", "persuasão", "influência social",
        "liderança", "trabalho em equipe", "cultura organizacional",
        "personalidade", "traços de personalidade", "Big Five",
        "temperamento", "caráter", "self", "autoestima", "autoconceito",
        "teoria das inteligências múltiplas", "inteligência fluida",
        "inteligência cristalizada", "QI", "teste psicológico",
        "esquizofrenia", "transtorno bipolar", "TDAH", "TEA", "autismo",
        "transtorno de personalidade", "borderline", "narcisista",
        "vício", "dependência química", "compulsão", "transtorno alimentar",
        "suicídio", "prevenção ao suicídio", "crise", "intervenção em crise",
        "psicologia positiva", "florescimento humano", "felicidade", "bem-estar",
        "mindfulness", "atenção plena", "meditação", "autocompaixão",
        "psicologia esportiva", "psicologia escolar", "psicologia jurídica",
        "psicologia hospitalar", "psicologia da saúde",
        "fenomenologia existencial", "análise existencial",
        # ========== COMPORTAMENTO HUMANO E MANIPULAÇÃO SENSORIAL/PSICOLÓGICA ==========
        "comportamento humano", "conduta", "ação humana", "tomada de decisão",
        "influência social", "conformidade", "obediência", "submissão",
        "persuasão", "retórica persuasiva", "argumentação", "propaganda",
        "manipulação psicológica", "manipulação emocional", "chantagem emocional",
        "gaslighting", "abuso psicológico", "coerção", "intimidação",
        "manipulação sensorial", "estímulo sensorial", "percepção subliminar",
        "mensagem subliminar", "priming", "enquadramento cognitivo", "framing",
        "nudge", "arquitetura de escolha", "empurrão comportamental",
        "heurísticas", "vieses cognitivos", "viés de confirmação",
        "viés de ancoragem", "viés de disponibilidade", "viés de retrospecto",
        "efeito halo", "efeito manada", "pensamento de grupo", "polarização",
        "dissonância cognitiva", "autopersuasão", "racionalização",
        "neuromarketing", "neuroeconomia", "marketing sensorial",
        "marketing experiencial", "branding emocional", "storytelling persuasivo",
        "design persuasivo", "arquitetura da informação persuasiva",
        "psicologia das cores", "psicologia das formas", "design emocional",
        "gamificação persuasiva", "engajamento comportamental",
        "economia comportamental", "Thaler", "Kahneman", "Tversky",
        "teoria do empurrão", "choice architecture", "decisão sob incerteza",
        "aversão à perda", "contabilidade mental", "desconto hiperbólico",
        "comportamento do consumidor", "psicologia do consumo",
        "comportamento organizacional", "cultura corporativa",
        "liderança persuasiva", "carisma", "liderança transformacional",
        "comunicação não-violenta", "comunicação persuasiva",
        "técnicas de venda", "negociação", "barganha", "influência recíproca",
        "escassez", "autoridade", "simpatia", "prova social", "compromisso",
        "princípios de persuasão de Cialdini", "influência automática",
        "propaganda política", "propaganda ideológica", "lavagem cerebral",
        "doutrinação", "controle mental", "seita", "culto", "sectarismo",
        "desinformação", "fake news", "pós-verdade", "câmara de eco",
        "bolha informacional", "filtro bolha", "algoritmo de recomendação",
        "ciência da influência", "engenharia social", "hacking cognitivo",
        "manipulação de massa", "psicologia das multidões", "Le Bon",
        "comportamento coletivo", "contágio social", "viralização",
        "modulação comportamental", "condicionamento operante",
        "condicionamento clássico", "reforço positivo", "reforço negativo",
        "punição", "extinção", "modelagem comportamental", "shaping",
        "terapia cognitivo-comportamental aplicada", "reestruturação cognitiva",
        "biofeedback", "neurofeedback", "interface cérebro-máquina",
        "leitura de mente", "detecção de mentiras", "microexpressões",
        "inteligência emocional aplicada", "empatia", "rapport", "espelhamento",
        "linguagem corporal", "comunicação não-verbal", "proxêmica",
        "paralinguagem", "tom de voz", "expressão facial",
        "análise comportamental", "perfil criminal", "psicologia forense",
        "interrogatório", "entrevista investigativa", "detecção de engano",
        "psicologia da mentira", "engano", "autoengano",
        "manipulação defensiva", "resistência à persuasão", "inoculação",
        "ceticismo saudável", "pensamento crítico", "contra-manipulação",
    ],
    metodos_pesquisa=[
        "Análise conceitual", "Fenomenologia descritiva", "Hermenêutica",
        "Dialética", "Genealogia", "Arqueologia do saber",
        "Etnografia", "Observação participante", "Entrevista profunda",
        "Estudo de caso qualitativo", "Análise do discurso",
        "Psicanálise clínica", "Experimentação psicológica",
        "Pesquisa-ação", "Teoria fundamentada",
    ],
    tradicoes_epistemologicas=[
        "Racionalismo", "Empirismo", "Idealismo alemão",
        "Fenomenologia", "Existencialismo", "Estruturalismo",
        "Pós-estruturalismo", "Teoria Crítica", "Pragmatismo",
        "Filosofia Analítica", "Hermenêutica", "Pós-modernismo",
    ],
    ferramentas=[
        "NVivo", "ATLAS.ti", "MAXQDA", "SPSS", "R (análise qualitativa)",
        "Análise de conteúdo", "Análise temática", "Análise narrativa",
    ],
)

# =============================================================================
# 2. CIÊNCIAS SOCIAIS (Social Sciences)
# =============================================================================
SOCIAL_SCIENCES = Faculdade(
    id="social_sciences",
    nome="Ciências Sociais Aplicadas",
    nome_en="Social Sciences",
    descricao="Economia, política, direito, comunicação e relações internacionais — "
               "o estudo das estruturas, processos e instituições que organizam a vida coletiva.",
    subdisciplinas=[
        "Economia", "Ciência Política", "Direito", "Comunicação Social",
        "Relações Internacionais", "Administração", "Contabilidade",
        "Serviço Social", "Demografia", "Urbanismo",
        "Geografia Humana", "Geografia Econômica", "Geografia Política",
        "Geopolítica", "Geografia Urbana", "Geografia Rural",
        "Geografia da População", "Geografia Cultural", "Geografia Histórica",
        "Ordenamento Territorial", "Planejamento Regional e Urbano",
        "Geoprocessamento Aplicado às Ciências Sociais",
    ],
    conceitos=[
        "mercado", "oferta", "demanda", "preço", "valor", "moeda", "crédito",
        "inflação", "juros", "câmbio", "PIB", "desenvolvimento", "crescimento",
        "capitalismo", "socialismo", "neoliberalismo", "keynesianismo",
        "estado", "governo", "soberania", "democracia", "república",
        "cidadania", "direitos humanos", "direitos fundamentais",
        "constituição", "lei", "norma jurídica", "jurisprudência",
        "devido processo legal", "ampla defesa", "contraditório",
        "propriedade", "contrato", "responsabilidade civil",
        "opinião pública", "mídia", "esfera pública", "agenda-setting",
        "enquadramento", "propaganda", "persuasão", "espiral do silêncio",
        "poder", "autoridade", "legitimidade", "representação",
        "participação", "movimentos sociais", "sociedade civil organizada",
        "globalização", "multilateralismo", "supranacionalidade",
        "diplomacia", "conflito", "cooperação", "integração regional",
        "bloco econômico", "comércio internacional", "protecionismo",
        "livre comércio", "vantagem comparativa", "cadeias globais de valor",
        "desigualdade", "pobreza", "exclusão social", "mobilidade social",
        "políticas públicas", "bem-estar social", "estado de direito",
        "accountability", "transparência", "governança", "corrupção",
        "desenvolvimento sustentável", "ESG", "externalidades",
        "bens públicos", "recursos comuns", "tragédia dos comuns",
    ],
    metodos_pesquisa=[
        "Econometria", "Séries temporais", "Dados em painel",
        "Experimentos aleatorizados", "Quase-experimentos",
        "Diferenças-em-diferenças", "Variável instrumental",
        "Regressão descontínua", "Pesquisa eleitoral", "Survey",
        "Análise de redes sociais", "Análise de conteúdo",
        "Jurimetria", "Análise documental", "Estudo comparativo",
    ],
    tradicoes_epistemologicas=[
        "Positivismo", "Behaviorismo", "Institucionalismo",
        "Escolha Racional", "Marxismo", "Estruturalismo",
        "Pós-positivismo", "Construtivismo social",
        "Teoria Crítica", "Feminismo", "Pós-colonialismo",
        "Economia Comportamental", "Teoria dos Jogos",
    ],
    ferramentas=[
        "Stata", "R", "Python (pandas, statsmodels)", "SPSS",
        "EViews", "Gretl", "QGIS", "Gephi", "NodeXL",
        "LaTeX", "Zotero", "Mendeley",
    ],
)

# =============================================================================
# 3. ENGENHARIA (Engineering)
# =============================================================================
ENGINEERING = Faculdade(
    id="engineering",
    nome="Engenharia",
    nome_en="Engineering",
    descricao="Engenharia de software, sistemas, elétrica, mecânica e computação — "
               "a arte e ciência de projetar, construir e otimizar sistemas tecnológicos.",
    subdisciplinas=[
        "Engenharia de Software", "Engenharia de Sistemas", "Engenharia Elétrica",
        "Engenharia Mecânica", "Engenharia de Computação", "Engenharia Civil",
        "Engenharia de Produção", "Engenharia Química", "Engenharia Aeroespacial",
        "Engenharia Biomédica", "Engenharia Ambiental", "Engenharia de Materiais",
    ],
    conceitos=[
        "sistema", "arquitetura", "componente", "módulo", "interface",
        "requisito", "especificação", "design", "implementação",
        "teste", "validação", "verificação", "manutenção",
        "refatoração", "padrão de projeto", "anti-pattern",
        "acoplamento", "coesão", "encapsulamento", "abstração",
        "herança", "polimorfismo", "composição", "delegação",
        "concorrência", "paralelismo", "assincronia", "distribuição",
        "tolerância a falhas", "resiliência", "disponibilidade",
        "escalabilidade", "desempenho", "latência", "throughput",
        "segurança", "privacidade", "autenticação", "autorização",
        "criptografia", "protocolo", "API", "middleware",
        "container", "orquestração", "microserviço", "monolito",
        "DevOps", "CI/CD", "infraestrutura como código",
        "observabilidade", "monitoramento", "logging", "métrica",
        "alerta", "SLA", "SLO", "SLI", "confiabilidade",
        "malha", "grade", "nuvem", "edge computing", "IoT",
        "sistema embarcado", "tempo real", "sistema crítico",
        "modelagem", "simulação", "protótipo", "MVP",
        "qualidade", "métrica de software", "dívida técnica",
        "processo", "metodologia ágil", "Scrum", "Kanban",
        "lean", "seis sigma", "TQM", "PDCA", "melhoria contínua",
    ],
    metodos_pesquisa=[
        "Engenharia experimental", "A/B testing", "Testes de hipótese",
        "Análise de falhas", "Análise de modos de falha (FMEA)",
        "Análise de causa raiz", "Design of Experiments (DoE)",
        "Análise de sensibilidade", "Simulação Monte Carlo",
        "Modelagem matemática", "Otimização", "Teoria das filas",
    ],
    tradicoes_epistemologicas=[
        "Positivismo engenharia", "Pragmatismo tecnológico",
        "Racionalismo aplicado", "Empirismo experimental",
        "Construtivismo sociotécnico", "Design Thinking",
        "Systems Thinking", "Cibernética", "Teoria Geral de Sistemas",
    ],
    ferramentas=[
        "Python", "Go", "Rust", "Java", "C++", "TypeScript",
        "Docker", "Kubernetes", "Terraform", "Ansible",
        "Jenkins", "GitHub Actions", "GitLab CI", "ArgoCD",
        "Prometheus", "Grafana", "ELK Stack", "Datadog",
        "VS Code", "JetBrains", "Vim", "Git", "Linux",
    ],
)

# =============================================================================
# 4. LETRAS & LINGUÍSTICA (Literary & Linguistic)
# =============================================================================
LITERARY_LINGUISTIC = Faculdade(
    id="literary_linguistic",
    nome="Letras e Linguística",
    nome_en="Literary and Linguistic Studies",
    descricao="Literatura, linguística, filologia, semiótica e tradução — "
               "o estudo da linguagem humana em suas dimensões estética, estrutural, histórica e cognitiva.",
    subdisciplinas=[
        "Literatura", "Literatura Universal", "Linguística", "Filologia", "Semiótica",
        "Tradução", "Letras Clássicas", "Letras Modernas",
        "Teoria Literária", "Literatura Comparada", "Poética",
        "Retórica", "Estilística", "Fonética", "Fonologia",
        "Morfologia", "Sintaxe", "Semântica", "Pragmática",
        "Sociolinguística", "Psicolinguística", "Neurolinguística",
        "Linguística Computacional", "Análise do Discurso",
        "Literatura Brasileira", "Literatura Portuguesa",
        "Literatura Inglesa", "Literatura Americana", "Literatura Francesa",
        "Literatura Alemã", "Literatura Italiana", "Literatura Espanhola",
        "Literatura Russa", "Literatura Japonesa", "Literatura Chinesa",
        "Literatura Africana", "Literatura Latino-Americana",
        "Literatura Árabe", "Literatura Indiana", "Literatura Grega Clássica",
        "Literatura Latina", "Literatura Medieval", "Literatura Renascentista",
    ],
    conceitos=[
        "signo", "significante", "significado", "referente",
        "símbolo", "ícone", "índice", "código", "mensagem",
        "canal", "emissor", "receptor", "ruído", "redundância",
        "entropia", "informação", "língua", "fala", "linguagem",
        "discurso", "texto", "contexto", "intertextualidade",
        "metáfora", "metonímia", "sinédoque", "ironia", "paradoxo",
        "narrativa", "enredo", "personagem", "narrador", "foco narrativo",
        "tempo", "espaço", "trama", "conflito", "clímax", "desfecho",
        "gênero literário", "épico", "lírico", "dramático", "romance",
        "conto", "poesia", "ensaio", "crônica", "epopeia", "tragédia",
        "comédia", "sátira", "utopia", "distopia", "realismo",
        "modernismo", "pós-modernismo", "barroco", "romantismo",
        "classicismo", "naturalismo", "simbolismo", "vanguardas",
        "morfema", "fonema", "alofone", "alomorfe", "léxico",
        "sintagma", "paradigma", "sincronia", "diacronia",
        "competência", "desempenho", "gramática universal",
        "ato de fala", "implicatura", "pressuposição", "inferência",
        "polissemia", "homonímia", "sinonímia", "antonímia", "hiperonímia",
        "coerência", "coesão", "progressão referencial", "tema", "rema",
        "tradução", "transcriação", "equivalência", "fidelidade", "estrangeirização",
        "domesticação", "intraduzibilidade", "retextualização",
        # ========== LITERATURA UNIVERSAL ==========
        "literatura universal", "cânone ocidental", "cânone literário",
        "Homero", "Ilíada", "Odisseia", "épica clássica",
        "Sófocles", "Édipo Rei", "Antígona", "tragédia grega",
        "Eurípides", "Medeia", "As Bacantes",
        "Aristófanes", "comédia grega", "as nuvens", "lisístrata",
        "Virgílio", "Eneida", "épica latina", "Ovídio", "Metamorfoses",
        "Dante Alighieri", "Divina Comédia", "Inferno", "Purgatório", "Paraíso",
        "Petrarca", "Cancioneiro", "soneto", "Francesco Petrarca",
        "Boccaccio", "Decamerão", "novela renascentista",
        "Camões", "Os Lusíadas", "epopeia portuguesa",
        "Miguel de Cervantes", "Dom Quixote", "romance moderno",
        "William Shakespeare", "Hamlet", "Macbeth", "Romeu e Julieta",
        "Otelo", "Rei Lear", "A Tempestade", "sonetos shakespearianos",
        "Molière", "Tartufo", "O Misantropo", "comédia francesa",
        "Goethe", "Fausto", "Werther", "romantismo alemão",
        "Victor Hugo", "Os Miseráveis", "Notre-Dame de Paris",
        "Honoré de Balzac", "Comédia Humana", "realismo francês",
        "Gustave Flaubert", "Madame Bovary",
        "Stendhal", "O Vermelho e o Negro",
        "Machado de Assis", "Dom Casmurro", "Memórias Póstumas de Brás Cubas",
        "Quincas Borba", "realismo brasileiro",
        "José de Alencar", "Iracema", "O Guarani", "romantismo brasileiro",
        "Guimarães Rosa", "Grande Sertão: Veredas",
        "Clarice Lispector", "A Hora da Estrela", "A Paixão Segundo GH",
        "Jorge Amado", "Gabriela Cravo e Canela", "Capitães da Areia",
        "Graciliano Ramos", "Vidas Secas", "São Bernardo",
        "Carlos Drummond de Andrade", "poesia moderna brasileira",
        "João Cabral de Melo Neto", "Morte e Vida Severina",
        "Fernando Pessoa", "heterônimos", "Mensagem", "poesia portuguesa",
        "Eça de Queirós", "Os Maias", "O Primo Basílio",
        "Fiódor Dostoiévski", "Crime e Castigo", "Os Irmãos Karamázov",
        "Lev Tolstói", "Guerra e Paz", "Anna Karenina",
        "Tchekhov", "O Jardim das Cerejeiras", "conto russo",
        "Franz Kafka", "A Metamorfose", "O Processo", "O Castelo",
        "James Joyce", "Ulisses", "Finnegans Wake", "fluxo de consciência",
        "Virginia Woolf", "Mrs Dalloway", "Ao Farol",
        "Marcel Proust", "Em Busca do Tempo Perdido",
        "Gabriel García Márquez", "Cem Anos de Solidão", "realismo mágico",
        "Jorge Luis Borges", "Ficções", "O Aleph", "labirinto borgiano",
        "Pablo Neruda", "Canto Geral", "poesia latino-americana",
        "Mario Vargas Llosa", "A Cidade e os Cachorros",
        "Toni Morrison", "Amada", "literatura afro-americana",
        "Chimamanda Ngozi Adichie", "Americanah", "literatura africana",
        "Milan Kundera", "A Insustentável Leveza do Ser",
        "Italo Calvino", "As Cidades Invisíveis",
        "Albert Camus", "O Estrangeiro", "existencialismo literário",
        "Haruki Murakami", "Kafka à Beira-Mar", "literatura japonesa contemporânea",
        "Orhan Pamuk", "Istambul", "literatura turca",
        "José Saramago", "Ensaio sobre a Cegueira", "O Evangelho Segundo Jesus Cristo",
        "Mia Couto", "Terra Sonâmbula", "literatura moçambicana",
        "Lima Barreto", "Triste Fim de Policarpo Quaresma",
        "Euclides da Cunha", "Os Sertões",
        "épica medieval", "Beowulf", "Canção de Rolando", "Cantar de Mio Cid",
        "Nibelungos", "arturiana", "Rei Artur", "cavaleiros da Távola Redonda",
        "literatura japonesa clássica", "Genji", "haikai", "Bashô",
        "As Mil e Uma Noites", "literatura árabe", "Shahriar e Sherazade",
        "literatura chinesa clássica", "Sun Tzu", "Arte da Guerra",
        "literatura indiana", "Mahabharata", "Ramayana", "Bhagavad Gita",
        "prêmio Nobel de literatura", "escrita criativa", "ofício do escritor",
        "literatura e sociedade", "literatura e política", "literatura e identidade",
        "literatura pós-colonial", "literatura migrante", "literatura diaspórica",
        "adaptação literária", "tradução intersemiótica", "cinema e literatura",
        "crítica genética", "crítica psicanalítica", "crítica feminista",
        "crítica marxista", "pós-crítica", "ecocrítica",
        "leitor modelo", "autor implícito", "pacto autobiográfico",
        "escrita de si", "autoficção", "testemunho literário",
    ],
    metodos_pesquisa=[
        "Análise literária", "Close reading", "Crítica textual",
        "Análise do discurso", "Análise de conteúdo", "Análise narrativa",
        "Estudo filológico", "Análise contrastiva", "Estudo de corpus",
        "Etnografia da fala", "Experimentos psicolinguísticos",
        "Análise fonética acústica", "Análise de erros",
        "Pesquisa-ação em linguística aplicada",
    ],
    tradicoes_epistemologicas=[
        "Estruturalismo", "Gerativismo", "Funcionalismo",
        "Formalismo Russo", "New Criticism", "Estética da Recepção",
        "Pós-estruturalismo", "Desconstrução", "Teoria do Discurso",
        "Linguística Cognitiva", "Análise Dialógica do Discurso",
        "Semiótica Peirceana", "Semiótica Greimasiana",
    ],
    ferramentas=[
        "Praat", "ELAN", "AntConc", "Sketch Engine", "CorpusLoader",
        "NLTK", "spaCy", "Stanza", "Python", "R",
        "Zotero", "LaTeX", "TEI XML", "Voyant Tools",
    ],
)

# =============================================================================
# 5. HISTÓRIA (Historical Studies)
# =============================================================================
HISTORICAL = Faculdade(
    id="historical",
    nome="História",
    nome_en="Historical Studies",
    descricao="História, arqueologia, historiografia e patrimônio — "
               "o estudo do tempo humano, das civilizações e da memória coletiva.",
    subdisciplinas=[
        "História Antiga", "História Medieval", "História Moderna",
        "História Contemporânea", "História do Brasil", "História da América",
        "História da África", "História da Ásia", "História Global",
        "Arqueologia", "Pré-história", "Historiografia",
        "História Cultural", "História Social", "História Econômica",
        "História Política", "História das Ideias", "História Intelectual",
        "História Digital", "História Pública", "Arquivologia",
        "Museologia", "História Oral", "Patrimônio Cultural",
    ],
    conceitos=[
        "tempo", "temporalidade", "periodização", "cronologia",
        "história", "memória", "esquecimento", "arquivo", "documento",
        "fonte histórica", "evidência", "testemunho", "rastro",
        "narrativa histórica", "interpretação", "explicação histórica",
        "causa", "consequência", "contingência", "necessidade",
        "progresso", "decadência", "ciclo", "ruptura", "continuidade",
        "evento", "estrutura", "conjuntura", "longa duração",
        "civilização", "império", "nação", "estado-nação", "nacionalismo",
        "colonialismo", "imperialismo", "pós-colonialismo", "descolonização",
        "revolução", "reforma", "rebelião", "guerra", "paz",
        "escravidão", "servidão", "trabalho", "classe", "casta",
        "gênero", "família", "parentesco", "geração", "infância",
        "cultura material", "cultura imaterial", "patrimônio",
        "arqueologia", "estratigrafia", "sítio arqueológico", "artefato",
        "pré-história", "paleolítico", "neolítico", "idade dos metais",
        "antiguidade", "medievo", "modernidade", "contemporaneidade",
        "renascimento", "iluminismo", "romantismo", "positivismo",
        "historicismo", "presentismo", "anacronismo",
        "micro-história", "história vista de baixo", "história das mentalidades",
        "história dos conceitos", "história do tempo presente",
        "patrimônio cultural", "preservação", "conservação", "restauração",
        "história digital", "big data histórico", "humanidades digitais",
    ],
    metodos_pesquisa=[
        "Análise documental", "Crítica de fontes", "Método histórico",
        "História comparada", "Análise serial", "Prosopografia",
        "História oral", "História de vida", "Análise de redes históricas",
        "Arqueologia experimental", "Análise estratigráfica",
        "Datação por carbono-14", "Paleografia", "Diplomática",
        "Análise quantitativa histórica", "Modelagem histórica",
    ],
    tradicoes_epistemologicas=[
        "Historicismo alemão", "Positivismo histórico", "Escola dos Annales",
        "Marxismo histórico", "Micro-história italiana", "História Cultural",
        "História Global", "Pós-modernismo histórico", "História Digital",
        "História Ambiental", "História Transnacional",
    ],
    ferramentas=[
        "NVivo", "ATLAS.ti", "Zotero", "Tropy", "Omeka",
        "Python (pandas, matplotlib)", "Gephi", "Palladio",
        "QGIS", "ArcGIS", "Tableau", "Git", "Markdown",
        "TEI XML", "JSON", "LaTeX", "Scrivener",
    ],
)

# =============================================================================
# 6. QUÂNTICA (Quantum Studies)
# =============================================================================
QUANTUM = Faculdade(
    id="quantum",
    nome="Ciências Quânticas",
    nome_en="Quantum Sciences",
    descricao="Computação quântica, informação quântica, tecnologias quânticas — "
               "o estudo e aplicação da mecânica quântica para computação, comunicação e simulação.",
    subdisciplinas=[
        "Computação Quântica", "Informação Quântica", "Criptografia Quântica",
        "Simulação Quântica", "Sensoriamento Quântico", "Comunicação Quântica",
        "Emaranhamento Quântico", "Correção de Erros Quânticos",
        "Algoritmos Quânticos", "Machine Learning Quântico",
        "Óptica Quântica", "Matéria Condensada Quântica",
        "Termodinâmica Quântica", "Teoria Quântica de Campos",
    ],
    conceitos=[
        "qubit", "superposição", "emaranhamento", "interferência quântica",
        "decoerência", "medida quântica", "colapso da função de onda",
        "operador", "hamiltoniano", "evolução unitária", "porta quântica",
        "circuito quântico", "algoritmo quântico", "transformada de Fourier quântica",
        "busca de Grover", "fatoração de Shor", "simulação quântica",
        "teletransporte quântico", "criptografia quântica", "BB84", "E91",
        "distribuição quântica de chaves", "QKD", "entropia de von Neumann",
        "informação mútua quântica", "fidelidade quântica", "traço parcial",
        "estado de Bell", "estado GHZ", "estado W", "cluster state",
        "código corretor quântico", "código de Shor", "código de superfície",
        "código estabilizador", "computação quântica topológica",
        "anyons", "computação quântica adiabática", "annealing quântico",
        "QAOA", "VQE", "algoritmo variacional", "QML", "quantum kernel",
        "quantum neural network", "tensor network", "MPS", "PEPS",
        "Qiskit", "Cirq", "PennyLane", "TensorFlow Quantum", "Braket",
        "supremacia quântica", "vantagem quântica", "ruído quântico",
        "NISQ", "computação quântica fault-tolerant",
        "emaranhamento multipartite", "desigualdade de Bell", "CHSH",
        "contextualidade quântica", "teorema de Kochen-Specker",
        "interpretações da mecânica quântica", "Copenhague", "Many Worlds",
        "variáveis ocultas", "Bohm", "QBismo", "de Broglie-Bohm",
    ],
    metodos_pesquisa=[
        "Simulação quântica em computadores clássicos",
        "Execução em hardware quântico real", "Experimentação em óptica quântica",
        "Análise de circuitos quânticos", "Tomografia quântica",
        "Randomized benchmarking", "Process tomography",
        "Quantum state tomography", "Análise de ruído e decoerência",
        "Teste de desigualdades de Bell", "Quantum error correction benchmarking",
    ],
    tradicoes_epistemologicas=[
        "Interpretação de Copenhague", "Interpretação de Many-Worlds",
        "Teoria de de Broglie-Bohm", "QBismo", "Interpretação Relacional",
        "Princípio Antrópico Quântico", "Pós-seleção",
        "Transacionalismo", "Teoria Quântica de Campos",
    ],
    ferramentas=[
        "Qiskit", "Cirq", "PennyLane", "TensorFlow Quantum",
        "Amazon Braket", "QuTiP", "ProjectQ", "Strawberry Fields",
        "Q#", "Python", "Jupyter", "LaTeX", "IBM Quantum Experience",
    ],
)

# =============================================================================
# 7. CIÊNCIAS EXATAS (Exact Sciences)
# =============================================================================
EXACT_SCIENCES = Faculdade(
    id="exact_sciences",
    nome="Ciências Exatas e da Terra",
    nome_en="Exact and Earth Sciences",
    descricao="Matemática, física, química, astronomia, biologia, geologia e geociências — "
               "o estudo das leis fundamentais da natureza, da vida em todas as suas escalas "
               "e dos processos que moldam a Terra e o cosmos.",
    subdisciplinas=[
        "Matemática Pura", "Matemática Aplicada", "Física Teórica",
        "Física Experimental", "Física de Partículas", "Astrofísica",
        "Cosmologia", "Química Orgânica", "Química Inorgânica",
        "Química Física", "Bioquímica", "Geociências", "Oceanografia",
        "Meteorologia", "Astronomia Observacional", "Astrobiologia",
        # NOVAS: Biologia e Ciências da Terra
        "Biologia Molecular", "Biologia Celular", "Genética", "Botânica",
        "Zoologia", "Ecologia", "Evolução", "Microbiologia", "Biotecnologia",
        "Geologia", "Geomorfologia", "Geofísica", "Hidrogeologia",
        "Hidrografia", "Pedologia", "Climatologia", "Geoquímica",
        "Paleontologia", "Mineralogia", "Petrologia", "Estratigrafia",
        "Oceanografia Física", "Oceanografia Biológica", "Limnologia",
        "Geoprocessamento", "Sensoriamento Remoto", "Cartografia",
    ],
    conceitos=[
        # MATEMÁTICA (existente)
        "número", "conjunto", "função", "limite", "derivada", "integral",
        "equação", "variável", "constante", "parâmetro", "espaço vetorial",
        "matriz", "transformação linear", "autovalor", "autovetor",
        "grupo", "anel", "corpo", "métrica", "topologia", "variedade",
        # FÍSICA (existente)
        "simetria", "invariância", "conservação", "lei física",
        "força", "energia", "momento", "campo", "onda", "partícula",
        "espaço", "tempo", "espaço-tempo", "relatividade", "gravidade",
        "eletromagnetismo", "termodinâmica", "entropia", "flecha do tempo",
        "mecânica quântica", "constante de Planck", "átomo", "elétron",
        "próton", "nêutron", "fóton", "quark", "glúon", "bóson de Higgs",
        "força fundamental", "modelo padrão", "supersimetria", "cordas",
        # QUÍMICA (existente)
        "molécula", "reação química", "ligação química",
        "elemento", "composto", "mol", "estequiometria", "equilíbrio químico",
        "catálise", "cinética química", "termodinâmica química",
        # ASTRONOMIA (existente)
        "estrela", "planeta", "galáxia", "nebulosa", "buraco negro",
        "supernova", "estrela de nêutrons", "big bang", "cosmologia",
        "matéria escura", "energia escura", "radiação cósmica de fundo",
        "exoplaneta", "habitabilidade", "zona habitável",
        # SISTEMAS DINÂMICOS (existente)
        "teoria do caos", "sistema dinâmico", "atrator", "bifurcação",
        "fractal", "auto-similaridade", "dimensão fractal", "criticalidade",
        # ========== NOVOS: BIOLOGIA ==========
        "vida", "célula", "organismo", "espécie", "população", "ecossistema",
        "biosfera", "habitat", "nicho ecológico", "biodiversidade",
        "DNA", "ácido desoxirribonucleico", "RNA", "ácido ribonucleico",
        "gene", "genoma", "cromossomo", "alelo", "genótipo", "fenótipo",
        "proteína", "enzima", "aminoácido", "síntese proteica",
        "código genético", "transcrição", "tradução", "replicação do DNA",
        "mutação", "recombinação genética", "evolução", "seleção natural",
        "deriva genética", "fluxo gênico", "especiação", "árvore filogenética",
        "último ancestral comum universal", "LUCA", "relógio molecular",
        "biomolécula", "carboidrato", "lipídeo", "nucleotídeo",
        "metabolismo", "catabolismo", "anabolismo", "fotossíntese",
        "respiração celular", "fermentação", "ciclo de Krebs", "ATP",
        "membrana celular", "núcleo celular", "mitocôndria", "cloroplasto",
        "ribossomo", "retículo endoplasmático", "complexo de Golgi",
        "divisão celular", "mitose", "meiose", "ciclo celular",
        "diferenciação celular", "célula-tronco", "apoptose", "necrose",
        "tecido", "órgão", "sistema biológico", "homeostase", "feedback biológico",
        "planta", "vegetal", "fotossíntese", "clorofila", "parede celular",
        "vacúolo", "xilema", "floema", "raiz", "caule", "folha", "flor", "fruto",
        "semente", "germinação", "polinização", "reprodução vegetal",
        "bioma", "floresta tropical", "savana", "deserto", "tundra", "taiga",
        "campo", "cerrado", "caatinga", "pampa", "mata atlântica", "amazônia",
        "pântano", "manguezal", "recife de coral", "zona costeira",
        "cadeia alimentar", "teia trófica", "produtor", "consumidor", "decompositor",
        "biogeografia", "biogeoquímica", "ciclo do carbono", "ciclo do nitrogênio",
        "ciclo da água", "ciclo do fósforo", "ciclo do oxigênio",
        "microrganismo", "bactéria", "vírus", "fungo", "protozoário", "alga",
        "anticorpo", "antígeno", "sistema imunológico", "vacina", "epidemiologia",
        "biologia molecular", "biologia sintética", "engenharia genética",
        "CRISPR", "edição genética", "transgênico", "clonagem", "sequenciamento",
        "PCR", "eletroforese", "microscopia eletrônica", "cultura de células",
        # ========== NOVOS: GEOLOGIA & GEOCIÊNCIAS ==========
        "Terra", "litosfera", "astenosfera", "manto", "núcleo terrestre",
        "crosta terrestre", "tectônica de placas", "placa tectônica",
        "deriva continental", "Pangeia", "limite convergente", "limite divergente",
        "falha geológica", "dobra", "orogênese", "cadeia de montanhas",
        "terremoto", "sismo", "onda sísmica", "epicentro", "magnitude",
        "vulcão", "magma", "lava", "vulcanismo", "erupção", "caldeira",
        "rocha", "rocha ígnea", "rocha sedimentar", "rocha metamórfica",
        "mineral", "cristal", "minério", "jazida", "depósito mineral",
        "intemperismo", "erosão", "sedimento", "sedimentação", "diagênese",
        "metamorfismo", "foliação", "ciclo das rochas", "estratigrafia",
        "fóssil", "paleontologia", "era geológica", "tempo geológico",
        "pré-cambriano", "paleozoico", "mesozoico", "cenozoico",
        "datação radiométrica", "carbono-14", "urânio-chumbo", "datação relativa",
        "índice fóssil", "registro fóssil", "extinção em massa",
        "geomorfologia", "relevo", "topografia", "altitude", "declividade",
        "vale", "montanha", "planalto", "planície", "depressão", "escarpamento",
        "bacia hidrográfica", "divisor de águas", "rede de drenagem",
        "rio", "córrego", "ribeirão", "afluente", "nascente", "foz", "delta",
        "estuário", "meandro", "planície de inundação", "terraço fluvial",
        "hidrografia", "hidrologia", "ciclo hidrológico", "precipitação",
        "evapotranspiração", "infiltração", "escoamento superficial", "percolação",
        "aquífero", "lençol freático", "lençol artesiano", "poço artesiano",
        "poço semi-artesiano", "água subterrânea", "recarga de aquífero",
        "nível d'água", "porosidade", "permeabilidade", "condutividade hidráulica",
        "água potável", "recurso hídrico", "gestão de bacias", "outorga d'água",
        "barragem", "represa", "reservatório", "irrigação", "drenagem",
        "oceanografia", "oceano", "mar", "corrente marinha", "onda oceânica",
        "maré", "plataforma continental", "talude continental", "fossa oceânica",
        "cadeia meso-oceânica", "recife", "atol", "circulação termoalina",
        "meteorologia", "climatologia", "atmosfera", "troposfera", "estratosfera",
        "camada de ozônio", "pressão atmosférica", "vento", "massas de ar",
        "frente fria", "frente quente", "ciclone", "anticiclone",
        "furacão", "tufão", "ciclone tropical", "tempestade", "tornado",
        "nuvem", "chuva", "neve", "granizo", "orvalho", "geada",
        "clima", "clima tropical", "clima temperado", "clima equatorial",
        "clima semiárido", "clima árido", "microclima",
        "mudança climática", "aquecimento global", "efeito estufa",
        "gás de efeito estufa", "CO₂", "metano", "óxido nitroso",
        "modelo climático", "IPCC", "cenário climático", "mitigação", "adaptação",
        "evento extremo", "seca", "inundação", "tempestade severa",
        "geoprocessamento", "SIG", "Sistema de Informação Geográfica",
        "sensoriamento remoto", "satélite", "imagem orbital", "Landsat",
        "MODIS", "SRTM", "LIDAR", "radar", "SONAR",
        "GPS", "GNSS", "georreferenciamento", "geocodificação",
        "cartografia", "mapa", "projeção cartográfica", "escala cartográfica",
        "curva de nível", "modelo digital de terreno", "grade regular",
        "análise espacial", "buffer", "overlay", "interpolação espacial",
        "krigagem", "inversa da distância", "geostatística",
        "topografia", "levantamento topográfico", "estação total", "teodolito",
        "pedologia", "solo", "horizonte do solo", "perfil do solo",
        "latossolo", "argissolo", "neossolo", "cambissolo", "gleissolo",
        "fertilidade do solo", "matéria orgânica do solo", "húmus",
        "conservação do solo", "manejo do solo", "erosão hídrica",
        "biologia do solo", "macrofauna do solo", "microfauna do solo",
        # ========== QUÍMICA-FÍSICA (Físico-Química) ==========
        "físico-química", "química-física", "termodinâmica química",
        "cinética química", "eletroquímica", "potencial eletroquímico",
        "eletrólise", "pilha galvânica", "célula eletroquímica",
        "equação de Nernst", "potencial de eletrodo", "corrosão",
        "mecânica estatística", "distribuição de Boltzmann",
        "função de partição", "ensemble canônico", "ensemble microcanônico",
        "gás ideal", "gás real", "equação de van der Waals",
        "lei dos gases", "pressão parcial", "fugacidade", "atividade química",
        "coeficiente de atividade", "solução ideal", "propriedade coligativa",
        "pressão osmótica", "elevação ebulioscópica", "abaixamento crioscópico",
        "diagrama de fases", "regra das fases de Gibbs", "ponto triplo",
        "ponto crítico", "fluido supercrítico", "transição de fase",
        "calorimetria", "entalpia", "energia livre de Gibbs",
        "energia livre de Helmholtz", "potencial químico",
        "constante de equilíbrio", "princípio de Le Chatelier",
        "lei de ação das massas", "grau de dissociação",
        "velocidade de reação", "ordem de reação", "lei de velocidade",
        "equação de Arrhenius", "energia de ativação", "catalisador",
        "mecanismo de reação", "etapa determinante", "intermediário de reação",
        "fotoquímica", "lei de Lambert-Beer", "rendimento quântico",
        "reação fotoquímica", "espectroscopia UV-Vis", "espectroscopia de infravermelho",
        "espectroscopia Raman", "ressonância magnética nuclear", "RMN",
        "espectrometria de massas", "difração de raios-X", "cristalografia",
        "química quântica", "orbital molecular", "Hückel", "DFT",
        "teoria do funcional da densidade", "Hartree-Fock",
        "cálculo de estrutura eletrônica", "propriedades moleculares",
        "química computacional", "modelagem molecular", "docking molecular",
        "química de superfícies", "adsorção", "catálise heterogênea",
        "cinética de Langmuir", "isoterma de adsorção",
        "eletrocatálise", "espectroscopia de fotoelétrons", "XPS",
    ],
    metodos_pesquisa=[
        "Método científico", "Experimentação controlada", "Modelagem matemática",
        "Simulação computacional", "Análise estatística", "Inferência bayesiana",
        "Análise de erro", "Propagação de incerteza", "Análise dimensional",
        "Teoria de grupos", "Métodos numéricos", "Elementos finitos",
        "Espectroscopia", "Cromatografia", "Microscopia", "Difração de raios-X",
        "PCR e sequenciamento genético", "Microscopia eletrônica",
        "Eletroforese em gel", "Cultura de células e tecidos",
        "Estratigrafia", "Datação radiométrica", "Análise de bacias",
        "Mapeamento geológico", "Sensoriamento remoto", "Geoprocessamento",
        "Análise de aquíferos", "Hidrogeologia integrada", "Modelagem de fluxo subterrâneo",
        "Análise de solo", "Amostragem ambiental", "Biogeoquímica",
        "Modelagem climática", "Previsão meteorológica numérica",
        "Análise de série temporal ambiental", "Geostatística",
    ],
    tradicoes_epistemologicas=[
        "Realismo científico", "Empirismo lógico", "Racionalismo crítico",
        "Positivismo lógico", "Instrumentalismo", "Platonismo matemático",
        "Intuicionismo", "Formalismo", "Estruturalismo matemático",
        "Falsificacionismo popperiano", "Paradigmas kuhnianos",
        "Selecionismo evolutivo", "Estruturalismo biológico",
        "Teoria de sistemas ecológicos", "Uniformitarismo geológico",
        "Catastrofismo", "Deriva continental", "Teoria de Gaia",
        "Pensamento complexo em ecologia",
    ],
    ferramentas=[
        "Python", "Julia", "MATLAB", "Mathematica", "Maple",
        "COMSOL", "ANSYS", "GROMACS", "Gaussian", "VASP",
        "LaTeX", "Git", "Jupyter", "NumPy", "SciPy", "SymPy",
        "TensorFlow", "PyTorch", "ROOT", "Geant4",
        # NOVAS: Biologia
        "BLAST", "Clustal Omega", "MEGA", "BioPython", "Bioconductor",
        "QGIS", "ArcGIS", "Spring", "gvSIG", "ERDAS Imagine", "ENVI",
        "GRASS GIS", "GeoDa", "TerrSet", "Google Earth Engine",
        "ModFlow", "FEFLOW", "Visual MODFLOW", "EPANET",
        "R (geoR, sp, raster, sf)", "Python (shapely, rasterio, folium)",
        "GMT (Generic Mapping Tools)", "Surfer", "RockWorks",
        "MicroStation", "AutoCAD MAP 3D", "Global Mapper",
    ],
)

# =============================================================================
# 8. ESTATÍSTICA & DATA SCIENCE (Statistics & Data Science)
# =============================================================================
STATISTICS_DS = Faculdade(
    id="statistics_ds",
    nome="Estatística e Ciência de Dados",
    nome_en="Statistics and Data Science",
    descricao="Estatística, probabilidade, machine learning e ciência de dados — "
               "a ciência de extrair conhecimento, padrões e previsões a partir de dados.",
    subdisciplinas=[
        "Estatística Teórica", "Estatística Aplicada", "Probabilidade",
        "Inferência Estatística", "Machine Learning", "Deep Learning",
        "Mineração de Dados", "Análise de Séries Temporais",
        "Estatística Bayesiana", "Estatística Não-paramétrica",
        "Bioestatística", "Econometria", "Pesquisa Operacional",
        "Otimização", "Teoria da Informação", "Aprendizagem por Reforço",
        "Processamento de Linguagem Natural", "Visão Computacional",
    ],
    conceitos=[
        "probabilidade", "variável aleatória", "distribuição", "esperança",
        "variância", "covariância", "correlação", "independência",
        "teorema central do limite", "lei dos grandes números",
        "inferência", "estimação", "estimador", "viés", "consistência",
        "eficiência", "intervalo de confiança", "teste de hipótese",
        "p-valor", "erro tipo I", "erro tipo II", "poder estatístico",
        "tamanho de efeito", "teste t", "ANOVA", "qui-quadrado",
        "regressão linear", "regressão logística", "GLM",
        "modelo misto", "efeitos aleatórios", "efeitos fixos",
        "bayesiano", "prior", "verossimilhança", "posterior",
        "MCMC", "Gibbs sampling", "Metropolis-Hastings",
        "série temporal", "estacionariedade", "ARIMA", "suavização",
        "machine learning", "aprendizagem supervisionada", "classificação",
        "regressão", "aprendizagem não-supervisionada", "clusterização",
        "dimensionalidade", "PCA", "t-SNE", "UMAP", "autoencoder",
        "árvore de decisão", "random forest", "gradient boosting",
        "XGBoost", "LightGBM", "CatBoost", "SVM", "k-NN",
        "rede neural", "deep learning", "CNN", "RNN", "LSTM", "Transformer",
        "atenção", "self-attention", "BERT", "GPT", "difusão",
        "aprendizagem por reforço", "Q-learning", "policy gradient",
        "DQN", "PPO", "SARSA", "bandit", "exploração vs explotação",
        "overfitting", "underfitting", "regularização", "Lasso", "Ridge",
        "validação cruzada", "bootstrap", "bagging", "boosting",
        "métrica", "acurácia", "precisão", "recall", "F1", "AUC",
        "curva ROC", "matriz de confusão", "curva de aprendizado",
        "entropia", "entropia cruzada", "divergência KL", "mutual information",
        "causalidade", "inferência causal", "Do-calculus", "DAG causal",
        "viés", "fairness", "equidade algorítmica", "explicabilidade",
        "interpretabilidade", "SHAP", "LIME", "feature importance",
    ],
    metodos_pesquisa=[
        "Delineamento experimental", "Pesquisa observacional",
        "Ensaio clínico randomizado", "Estudo de coorte", "Caso-controle",
        "Análise de sobrevivência", "Meta-análise", "Revisão sistemática",
        "Análise de poder", "Análise de sensibilidade", "Bootstrapping",
        "Testes permutacionais", "Análise bayesiana de dados",
        "Modelagem preditiva", "Análise de séries temporais",
    ],
    tradicoes_epistemologicas=[
        "Frequentismo", "Bayesianismo", "Empirismo estatístico",
        "Racionalismo inferencial", "Pragmatismo preditivo",
        "Criticalismo popperiano", "Empiricismo de machine learning",
    ],
    ferramentas=[
        "R", "Python", "Julia", "SAS", "SPSS", "Stata",
        "scikit-learn", "TensorFlow", "PyTorch", "JAX",
        "XGBoost", "LightGBM", "CatBoost", "Statsmodels",
        "Stan", "PyMC", "brms", "lme4", "caret", "tidymodels",
        "Pandas", "NumPy", "SciPy", "Matplotlib", "Seaborn", "Plotly",
        "D3.js", "Tableau", "Power BI", "Jupyter", "RStudio",
        "MLflow", "DVC", "Weights & Biases", "Neptune",
    ],
)

# =============================================================================
# 9. PROGRAMAÇÃO (Programming & Formal Languages)
# =============================================================================
PROGRAMMING = Faculdade(
    id="programming",
    nome="Programação e Linguagens Formais",
    nome_en="Programming and Formal Languages",
    descricao="Linguagens de programação, compiladores, sistemas formais e paradigmas — "
               "a arte e ciência da expressão computacional em múltiplos paradigmas.",
    subdisciplinas=[
        "Linguagens de Programação", "Compiladores", "Paradigmas de Programação",
        "Programação Funcional", "Programação Orientada a Objetos",
        "Programação Lógica", "Programação Concorrente", "Teoria dos Tipos",
        "Linguagens Formais", "Autômatos", "Computabilidade",
        "Sistemas de Tipos", "Análise de Programas", "Verificação Formal",
        "Metaprogramação", "DSL", "Linguagens Esotéricas",
    ],
    conceitos=[
        "linguagem de programação", "sintaxe", "semântica", "pragmática",
        "gramática formal", "BNF", "EBNF", "AST", "parser",
        "compilador", "interpretador", "transpilador", "JIT", "AOT",
        "tipo", "tipo estático", "tipo dinâmico", "inferência de tipos",
        "tipo dependente", "tipo algébrico", "GADT", "tipo existencial",
        "classe", "objeto", "herança", "composição", "mixim", "trait",
        "interface", "protocolo", "abstração", "encapsulamento",
        "função", "lambda", "closure", "currying", "aplicação parcial",
        "monada", "functor", "aplicativo", "category theory",
        "efeito colateral", "pureza", "imutabilidade", "transparência referencial",
        "recursão", "recursão de cauda", "iteração", "ponto fixo",
        "continuação", "corrotina", "gerador", "async", "await",
        "fibra", "thread", "processo", "Green thread", "Goroutine",
        "canal", "ator", "CSP", "memória compartilhada", "mutex",
        "semáforo", "transação de memória", "STM", "lock-free",
        "padrão de design", "GoF", "arquitetura hexagonal", "clean architecture",
        "DDD", "CQRS", "Event Sourcing", "arquitetura orientada a eventos",
        "sistema de tipos", "soundness", "completude", "decidibilidade",
        "lambda calculus", "sistema F", "CoC", "provas como programas",
        "Curry-Howard", "isomorfismo de Curry-Howard", "lógica linear",
        "autômato", "máquina de Turing", "equivalência de Turing",
        "problema da parada", "indecidibilidade", "NP-completude",
        "redução", "classe de complexidade", "P", "NP", "EXP",
        "memória", "stack", "heap", "GC", "ARC", "cópia", "movimento",
        "ponteiro", "referência", "borrowing", "lifetime", "ownership",
        "Go", "Rust", "Python", "Julia", "Haskell", "OCaml",
        "Erlang", "Elixir", "Clojure", "Scheme", "Racket",
        "Prolog", "C", "C++", "Zig", "Nim", "TypeScript",
    ],
    metodos_pesquisa=[
        "Análise estática de programas", "Prova formal de correção",
        "Model checking", "Teste de software", "Property-based testing",
        "Benchmarking experimental", "Análise de complexidade",
        "Prova de teoremas", "Síntese de programas",
        "Estudo comparativo de linguagens", "Análise de segurança",
    ],
    tradicoes_epistemologicas=[
        "Racionalismo computacional", "Empirismo de software",
        "Formalismo matemático", "Pragmatismo de engenharia",
        "Platonismo computacional", "Construtivismo algorítmico",
        "Funcionalismo lógico", "Pós-modernismo de software",
    ],
    ferramentas=[
        "Python", "Go", "Rust", "Julia", "Haskell", "OCaml",
        "Coq", "Agda", "Idris", "Lean", "Z3", "ProVerif",
        "LLVM", "GCC", "Clang", "SML", "ANTLR", "Happy", "Alex",
        "Git", "GitHub", "GitLab", "Linux", "VS Code", "Emacs", "Vim",
        "Jupyter", "Docker", "Podman", "QEMU", "GDB", "Perf",
    ],
)

# =============================================================================
# 10. INTERDISCIPLINAR (Transversal / Metaciência)
# =============================================================================
INTERDISCIPLINARY = Faculdade(
    id="interdisciplinary",
    nome="Estudos Interdisciplinares e Transversais",
    nome_en="Interdisciplinary and Transversal Studies",
    descricao="Metaciência, complexidade, teoria de sistemas, inovação e neurociência — "
               "o estudo da própria produção de conhecimento, das conexões entre disciplinas "
               "e dos fenômenos emergentes que transcendem fronteiras disciplinares.",
    subdisciplinas=[
        "Metaciência", "Complexidade", "Teoria de Sistemas", "Cibernética",
        "Innovation Studies", "Neurociência", "Ciência Cognitiva",
        "Estudos de Ciência e Tecnologia (STS)", "Transdisciplinaridade",
        "Futurismo", "Epistemologia", "Filosofia da Ciência",
        "Ética em Pesquisa", "Open Science", "Responsible Research",
        "Teoria das Redes", "Ciência das Redes", "Tecnologia Social",
        "Design Science", "Pesquisa-Desenvolvimento-Inovação",
    ],
    conceitos=[
        "complexidade", "emergência", "auto-organização", "caos",
        "sistema adaptativo complexo", "rede", "grafo", "hub",
        "conectividade", "small world", "scale-free", "resiliência",
        "robustez", "fragilidade", "antifragilidade", "cisne negro",
        "meta-conhecimento", "conhecimento do conhecimento", "episteme",
        "paradigma", "revolução científica", "programa de pesquisa",
        "crise", "anomalia", "ciência normal", "ciência extraordinária",
        "interdisciplinaridade", "multidisciplinaridade", "transdisciplinaridade",
        "boundary object", "tradução", "mediação", "hibridização",
        "conhecimento tácito", "conhecimento explícito", "SECI",
        "inovação", "invenção", "difusão", "tecnologia disruptiva",
        "paradigma tecnológico", "trajetória tecnológica", "regime tecnológico",
        "sistema de inovação", "hélice tríplice", "hélice quádrupla",
        "modo 1 de produção de conhecimento", "modo 2", "ciência pós-acadêmica",
        "análise de redes sociais", "homofilia", "força dos laços fracos",
        "embeddedness", "capital social", "confiança", "cooperação",
        "cognição", "mente", "consciência", "percepção", "atenção",
        "memória de trabalho", "memória de longo prazo", "aprendizagem",
        "plasticidade neural", "neuroplasticidade", "neurônio", "sinapse",
        "neurotransmissor", "circuito neural", "mapa cognitivo",
        "modelo mental", "esquema", "heuristic", "viés cognitivo",
        "raciocínio", "tomada de decisão", "resolução de problemas",
        "criatividade", "insight", "flow", "expertise", "deliberação",
        "ciência aberta", "reprodutibilidade", "replicabilidade",
        "pré-registro", "registro de ensaio clínico", "dados abertos",
        "crise de replicação", "p-hacking", "HARKing", "viés de publicação",
        "meta-análise", "revisão sistemática", "evidência", "certeza",
        "incerteza", "ignorância", "epistemologia da ignorância",
        "estudos de futuro", "cenário", "prospecção", "backcasting",
        "antecipação", "dinâmica de sistemas", "ciclo de feedback",
        "causalidade circular", "alavancagem", "ponto de inflexão",
        "problema wicked", "problema super wicked", "poli-crise",
        "grande desafio", "transição sociotécnica", "sustentabilidade",
        "limites planetários", "antropoceno", "capitaloceno",
        "responsabilidade social da ciência", "engajamento público",
        "ciência cidadã", "pesquisa participativa", "co-criação",
    ],
    metodos_pesquisa=[
        "Meta-pesquisa", "Meta-análise", "Revisão sistemática da literatura",
        "Análise de redes", "Modelagem de sistemas dinâmicos",
        "Método de cenários", "Delphi", "Análise de stakeholders",
        "Pesquisa-ação", "Design Science Research", "Mixed methods",
        "Análise bibliométrica", "Cienciometria", "Análise de co-palavras",
        "Análise de co-citação", "Análise longitudinal de paradigmas",
    ],
    tradicoes_epistemologicas=[
        "Complexidade e Caos", "Cibernética de 2ª ordem",
        "Pensamento Sistêmico", "Pragmatismo epistemológico",
        "Naturalismo metodológico", "Construtivismo radical",
        "Realismo crítico", "Relativismo epistemológico",
        "Anarquismo metodológico", "Open Science movement",
        "Post-normal science", "Responsible Research and Innovation (RRI)",
    ],
    ferramentas=[
        "Python", "R", "Gephi", "NodeXL", "NetLogo", "Vensim",
        "Stella", "Cytoscape", "VOSviewer", "Bibliometrix",
        "Zotero", "LaTeX", "Jupyter", "NVivo", "MAXQDA",
        "GitHub", "Zenodo", "OSF", "Figshare",
    ],
)


# =============================================================================
# 11. CIÊNCIAS DA SAÚDE (Health Sciences)
# =============================================================================
HEALTH_SCIENCES = Faculdade(
    id="health_sciences",
    nome="Ciências da Saúde",
    nome_en="Health Sciences",
    descricao="Medicina, psiquiatria, farmacologia, enfermagem e biomedicina — "
               "o estudo da saúde humana, dos processos patológicos, dos tratamentos "
               "e da promoção do bem-estar físico e mental.",
    subdisciplinas=[
        "Medicina Geral", "Clínica Médica", "Cirurgia Geral",
        "Pediatria", "Ginecologia e Obstetrícia", "Cardiologia",
        "Neurologia", "Oncologia", "Ortopedia", "Oftalmologia",
        "Dermatologia", "Psiquiatria", "Saúde Mental",
        "Farmacologia", "Farmácia Clínica", "Farmácia Hospitalar",
        "Enfermagem", "Nutrição", "Odontologia",
        "Biomedicina", "Análises Clínicas", "Fisioterapia",
        "Terapia Ocupacional", "Fonoaudiologia", "Educação Física",
        "Medicina Preventiva", "Saúde Coletiva", "Epidemiologia",
        "Bioética", "Anatomia", "Fisiologia", "Patologia",
        "Imunologia", "Microbiologia Médica", "Parasitologia Médica",
        "Genética Médica", "Biologia Molecular Aplicada à Saúde",
        "Radiologia", "Diagnóstico por Imagem", "Medicina Nuclear",
        "Anestesiologia", "Medicina Intensiva", "Medicina de Emergência",
        "Infectologia", "Reumatologia", "Endocrinologia",
        "Gastroenterologia", "Pneumologia", "Nefrologia", "Hematologia",
        "Geriatria", "Medicina do Esporte", "Medicina do Trabalho",
        "Acupuntura", "Homeopatia", "Medicina Integrativa",
    ],
    conceitos=[
        # ANATOMIA E FISIOLOGIA
        "corpo humano", "sistema nervoso", "sistema cardiovascular",
        "sistema respiratório", "sistema digestório", "sistema endócrino",
        "sistema imunológico", "sistema muscular", "sistema esquelético",
        "sistema reprodutor", "sistema urinário", "sistema tegumentar",
        "cérebro", "coração", "pulmão", "fígado", "rim", "estômago",
        "intestino", "pâncreas", "baço", "tireoide", "hipófise",
        "neurônio", "sinapse", "neurotransmissor", "hormônio",
        "sangue", "hemácia", "leucócito", "plaqueta", "plasma",
        "osso", "músculo", "articulação", "ligamento", "tendão",
        "pele", "mucosa", "glândula", "órgão dos sentidos",
        "visão", "audição", "olfato", "paladar", "tato", "propriocepção",
        "homeostase", "feedback fisiológico", "regulação hormonal",
        "ciclo circadiano", "metabolismo basal", "termorregulação",
        # PATOLOGIA E DOENÇAS
        "doença", "patologia", "síndrome", "transtorno", "distúrbio",
        "inflamação", "infecção", "tumor", "neoplasia", "metástase",
        "febre", "dor", "edema", "hemorragia", "isquemia", "necrose",
        "hipertensão arterial", "diabetes mellitus", "obesidade",
        "câncer", "doença cardiovascular", "AVC", "infarto",
        "doença infecciosa", "bactéria patogênica", "infecção viral",
        "HIV", "AIDS", "hepatite", "tuberculose", "pneumonia",
        "COVID-19", "pandemia", "endemia", "epidemia",
        "doença autoimune", "artrite reumatoide", "lúpus",
        "alergia", "asma", "rinite", "anafilaxia",
        "doença neurodegenerativa", "Alzheimer", "Parkinson",
        "esclerose múltipla", "ELA", "demência",
        # PSIQUIATRIA
        "saúde mental", "transtorno mental", "psiquiatria",
        "depressão maior", "transtorno depressivo", "distimia",
        "transtorno bipolar", "mania", "hipomania", "ciclotimia",
        "transtorno de ansiedade", "ansiedade generalizada", "pânico",
        "fobia social", "fobia específica", "agorafobia",
        "TOC", "transtorno obsessivo-compulsivo",
        "TEPT", "transtorno de estresse pós-traumático",
        "transtorno do pânico", "crise de ansiedade",
        "esquizofrenia", "psicose", "delírio", "alucinação",
        "transtorno esquizoafetivo", "transtorno delirante",
        "TDAH", "transtorno do déficit de atenção",
        "transtorno do espectro autista", "TEA", "autismo",
        "transtorno de personalidade", "borderline", "narcisista",
        "antissocial", "esquizoide", "dependente", "evitativo",
        "transtorno alimentar", "anorexia", "bulimia", "compulsão alimentar",
        "transtorno do sono", "insônia", "apneia", "narcolepsia",
        "transtorno por uso de substância", "dependência química",
        "alcoolismo", "tabagismo", "drogadição",
        "transtorno dissociativo", "transtorno de conversão",
        "somatização", "transtorno somatoforme",
        "suicídio", "comportamento suicida", "auto-mutilação",
        "crise psiquiátrica", "internação psiquiátrica",
        "psicofármaco", "antidepressivo", "ansiolítico", "lítio",
        "antipsicótico", "estabilizador de humor",
        "eletroconvulsoterapia", "ECT", "psicoterapia",
        "psiquiatria infantil", "psiquiatria geriátrica",
        "psiquiatria forense", "saúde mental global",
        # FARMACOLOGIA
        "farmacologia", "fármaco", "droga", "medicamento", "remédio",
        "farmacocinética", "absorção", "distribuição", "metabolização",
        "excreção", "meia-vida", "biodisponibilidade",
        "farmacodinâmica", "receptor", "agonista", "antagonista",
        "sítio ativo", "afinidade", "eficácia", "potência",
        "interação medicamentosa", "sinergismo", "antagonismo medicamentoso",
        "reação adversa", "efeito colateral", "toxicidade",
        "janela terapêutica", "índice terapêutico", "dose",
        "posologia", "via de administração", "oral", "intravenosa",
        "intramuscular", "subcutânea", "tópica", "inalatória",
        "analgésico", "anti-inflamatório", "antibiótico", "antiviral",
        "antifúngico", "antiparasitário", "antineoplásico",
        "anti-hipertensivo", "vasodilatador", "diurético",
        "anticoagulante", "antiagregante plaquetário",
        "hipoglicemiante", "insulina", "corticosteroide",
        "imunossupressor", "imunoestimulante", "vacina",
        "quimioterápico", "radioterápico", "terapia alvo",
        "medicamento genérico", "medicamento de referência",
        "farmacovigilância", "ensaios clínicos", "fase pré-clínica",
        "fase clínica", "randomizado", "duplo-cego", "placebo",
        "farmacogenômica", "farmacogenética", "medicina personalizada",
        "farmacoepidemiologia", "farmacoeconomia",
        "psicofarmacologia", "farmacologia clínica",
        # MEDICINA GERAL E CLÍNICA
        "semiologia", "exame clínico", "anamnese", "história clínica",
        "exame físico", "ausculta", "palpação", "percussão",
        "diagnóstico", "diagnóstico diferencial", "prognóstico",
        "terapêutica", "tratamento", "cura", "remissão", "paliativo",
        "prevenção", "prevenção primária", "prevenção secundária",
        "rastreamento", "check-up", "exame de rotina",
        "exame laboratorial", "hemograma", "bioquímica sérica",
        "urina", "fezes", "líquor", "biópsia",
        "exame de imagem", "radiografia", "ultrassonografia",
        "tomografia computadorizada", "TC", "ressonância magnética",
        "RM", "PET-Scan", "mamografia", "densitometria óssea",
        "eletrocardiograma", "ECG", "eletroencefalograma", "EEG",
        "endoscopia", "colonoscopia", "broncoscopia", "cistoscopia",
        "cateterismo cardíaco", "angiografia",
        "cirurgia", "cirurgia minimamente invasiva", "laparoscopia",
        "robótica cirúrgica", "transplante", "enxerto",
        "medicina de emergência", "primeiros socorros", "RCP",
        "UTI", "unidade de terapia intensiva", "ventilação mecânica",
        "hemodiálise", "diálise peritoneal",
        "nutrição clínica", "dieta hospitalar", "suporte nutricional",
        "enfermagem", "cuidados de enfermagem", "técnica de enfermagem",
        "humanização hospitalar", "acolhimento", "cuidado paliativo",
        "tanatologia", "luto", "processo de morte e morrer",
        # SAÚDE PÚBLICA E EPIDEMIOLOGIA
        "saúde pública", "saúde coletiva", "SUS", "sistema único de saúde",
        "atenção primária", "atenção secundária", "atenção terciária",
        "epidemiologia", "incidência", "prevalência", "morbidade",
        "mortalidade", "letalidade", "expectativa de vida",
        "fator de risco", "fator protetor", "determinante social",
        "promoção da saúde", "prevenção de doenças",
        "vigilância epidemiológica", "vigilância sanitária",
        "notificação compulsória", "surto", "epidemia", "pandemia",
        "imunização", "calendário vacinal", "cobertura vacinal",
        "saúde da criança", "saúde do adolescente", "saúde da mulher",
        "saúde do idoso", "saúde do trabalhador",
        "doença negligenciada", "medicina tropical",
        # BIOÉTICA E MEDICINA LEGAL
        "bioética", "princípios bioéticos", "autonomia", "beneficência",
        "não-maleficência", "justiça", "dilema ético",
        "consentimento informado", "termo de consentimento",
        "sigilo médico", "confidencialidade", "prontuário médico",
        "eutanásia", "ortotanásia", "distanásia", "testamento vital",
        "aborto", "reprodução assistida", "barriga de aluguel",
        "clonagem humana", "células-tronco embrionárias",
        "medicina legal", "perícia médica", "necropsia", "autópsia",
        "tanatologia forense", "traumatologia forense",
        "medicina do trabalho", "perícia ocupacional",
        # FISIOTERAPIA E REABILITAÇÃO
        "fisioterapia", "reabilitação", "cinesioterapia",
        "eletroterapia", "termoterapia", "hidroterapia",
        "massoterapia", "drenagem linfática", "quiropraxia",
        "osteopatia", "acupuntura", "reabilitação neurológica",
        "reabilitação cardíaca", "reabilitação respiratória",
        "Fonoaudiologia", "audiologia", "voz", "deglutição", "linguagem",
        "Terapia Ocupacional", "atividades da vida diária",
        "órtese", "prótese", "tecnologia assistiva",
        # NUTRIÇÃO
        "nutrição", "alimento", "nutriente", "caloria", "macronutriente",
        "proteína", "carboidrato", "gordura", "vitamina", "mineral",
        "fibra alimentar", "água", "hidratação",
        "dieta balanceada", "pirâmide alimentar", "guia alimentar",
        "desnutrição", "obesidade", "síndrome metabólica",
        "nutrição clínica", "terapia nutricional", "dieta hospitalar",
        "nutrição esportiva", "alimentação funcional", "nutracêutico",
        "fitoterapia", "plantas medicinais", "interação fármaco-nutriente",
        # ODONTOLOGIA
        "odonto", "odontologia", "dente", "cárie", "periodontite",
        "gengivite", "canal", "implante dentário", "prótese dentária",
        "ortodontia", "aparelho ortodôntico", "estética dental",
        "cirurgia bucomaxilofacial", "saúde bucal",
        "radiografia odontológica", "panorâmica",
        # MEDICINAS INTEGRATIVAS
        "medicina integrativa", "medicina complementar",
        "acupuntura chinesa", "medicina ayurvédica",
        "medicina tradicional chinesa", "fitoterapia chinesa",
        "homeopatia", "florais de Bach", "cromoterapia",
        "aromaterapia", "meditação terapêutica", "yoga terapêutica",
        "mindfulness clínico", "redução de estresse", "relaxamento",
    ],
    metodos_pesquisa=[
        "Ensaio clínico randomizado", "Estudo duplo-cego controlado",
        "Estudo de coorte prospectivo", "Estudo caso-controle",
        "Revisão sistemática", "Meta-análise", "Estudo transversal",
        "Série de casos", "Relato de caso", "Pesquisa translacional",
        "Pesquisa básica em biomedicina", "Experimentação animal",
        "Cultura de células", "Ensaios enzimáticos", "PCR em tempo real",
        "Sequenciamento genético aplicado", "Microscopia confocal",
        "Eletrofisiologia", "Patch-clamp", "Neuroimagem funcional",
        "fMRI", "PET", "EEG", "MEG", "Espectroscopia de massa",
        "Cromatografia líquida de alta eficiência", "HPLC",
        "Análise farmacocinética", "Modelagem PK/PD",
        "Bioestatística médica", "Análise de sobrevivência",
        "Curva ROC", "NNT", "NND", "Odds ratio", "Risco relativo",
        "Medicina baseada em evidências", "MBE",
    ],
    tradicoes_epistemologicas=[
        "Biomedicina", "Modelo biopsicossocial", "Medicina baseada em evidências",
        "Positivismo médico", "Fenomenologia da doença",
        "Antropologia médica", "Medicina narrativa",
        "Humanização da saúde", "Saúde coletiva", "Determinação social da saúde",
        "Teoria dos sistemas aplicada à saúde",
        "Medicina personalizada", "Medicina de precisão",
        "Farmacologia integrativa", "Neurociência translacional",
        "Psiquiatria biológica", "Psiquiatria psicodinâmica",
        "Saúde pública global", "Uma só saúde", "One Health",
    ],
    ferramentas=[
        "EPICLIN", "SPSS", "R (survival, meta, lme4)", "SAS", "Stata",
        "Python (scipy, statsmodels, biopython)", "GraphPad Prism",
        "ImageJ", "Fiji", "Napari", "Freesurfer", "SPM", "FSL",
        "BLAST", "BioPython", "Galaxy", "Qiime", "Mothur",
        "ChemAxon", "Schrödinger", "AutoDock", "PyMOL", "Chimera",
        "EndNote", "Zotero", "Mendeley", "LaTeX",
        "SUS", "DATASUS", "TabNet", "EpiInfo", "EpiData",
        "OpenEpi", "MedCalc", "Meta-Analyst", "RevMan",
        "Sistema de prontuário eletrônico", "MV", "Tasy", "Raia",
        "Stethoscope", "ecocardiógrafo", "eletrocardiógrafo",
        "Tomógrafo", "Ressonância magnética", "Ultrassom",
        "Laringoscópio", "broncoscópio", "endoscópio",
    ],
)

# =========================================================================
# Agrupamentos
# =========================================================================

ALL_FACULTIES: List[Faculdade] = [
    HUMAN_SCIENCES,
    SOCIAL_SCIENCES,
    ENGINEERING,
    LITERARY_LINGUISTIC,
    HISTORICAL,
    QUANTUM,
    EXACT_SCIENCES,
    STATISTICS_DS,
    PROGRAMMING,
    INTERDISCIPLINARY,
    HEALTH_SCIENCES,
]

FACULTY_MAP: Dict[str, Faculdade] = {f.id: f for f in ALL_FACULTIES}


def get_faculty(faculty_id: str) -> Optional[Faculdade]:
    """Retorna faculdade pelo ID."""
    return FACULTY_MAP.get(faculty_id)


def list_all_concepts() -> List[str]:
    """Retorna todos os conceitos de todas as faculdades."""
    result = []
    for fac in ALL_FACULTIES:
        result.extend(fac.conceitos)
    return result


def count_total_concepts() -> int:
    """Conta total de conceitos únicos em todas as faculdades."""
    return len(set(list_all_concepts()))
